### ISSUE TITLE
Potential Minor Adjustments to LC Logic (Inappropriate Application of DCP Tax)

### ISSUE THREAD

**Issue by apivarnik** [usbr/crmms#100]
While assisting @sbaker2423 with her SEIS modeling, we noticed some accounting was not adding up. There were a couple spots within the logic where it looks to be applying tax inappropriately. Need to run through this with LC and allow them to make final decision

**Comment by stighi** [comment]
After reviewing these items with Alex, the updates were made and committed in version 3.1.0.9001, and will be included in the January 2023 model runs.
