### ISSUE TITLE
Power method RW bug & update max iterations

### ISSUE THREAD

**Issue by sbaker2423** [usbr/crmms#101]
The Peak and Base and Peak Flow methods for solving for power (used at Powell, Mead, Flaming Gorge, Fontenelle, Crystal, Morrow Point and Blue Mesa) has been updated due bugs that surfaced during SEIS modeling. Here's some advice/description of issue from CADSWES:

> With this fix, you will need to set the Max Iterations slot on Powell to 1000. Currently it is 20. I would also recommend changing the Max Iterations to 1000 for any other reservoir using the Peak and Base method even though I did not see issues with any other reservoirs in my testing.
> 
> We changed how the Peak and Base method iterates when near the min operating head. Previously the iterative solution would stop as soon as a single iteration hit the min operating head, which resulted in an incorrect result for the Peak Flow or max release. Now it is allowed to continue iterating. Also, previously when called from a RPL function (e.g. GetMaxReleaseGivenInflow), when the result was at or below the min operating head, it did not return anything, which was what was causing the rule to terminate early. Now it returns a flow of zero in those cases to match how the method solves in dispatching.
> 
> With these changes, Rule Set Powell Outflow re-executes and recomputes new outflow values after higher priority rules change the TargetAnnualReleaseVolume or other dependent slots.
> 
> I was still seeing four max iteration warnings in Run Cycle 3. I was able to step through these and see that they were moving toward convergence but very slowly. Even though they did not converge within the criterion (5 cfs), they were close. They do not look like they are contributing to incorrect results. You might be able to modify data in the low end of the Best Generator Flow table or Tailwater Table to help these cases converge easier, but from a practical perspective, they are not causing a problem. 

The bug fixes are in 8.5.6 patch release. 

- [ ] We will need to update the res.Max Iterations slots on power reservoirs to 1000.

Description of issue/fix from CADSWES:

RW-6818 - Peak and Base Power method incorrectly handles operating head below min in RPL function
-----------------------------
In this bug, the GetMaxReleaseGivenInflow function was incorrectly terminating early for a reservoir using the Peak and Base Power method. Previously when called from a RPL function (e.g. GetMaxReleaseGivenInflow), when the computed Operating Head was at or below the Minimum Operating Head, the power method did not return a value causing the rule to terminate early. Now, the method returns a flow of zero in those cases to match how the method solves in dispatching. 

In addition, the iterative solution to compute Peak Flow for the Peak and Base and Peak Power methods stopped iterating and set a Peak Flow and Peak Power of zero as soon as a single iteration hit the minimum operating head. Now, it is allowed to continue iterating to produce correct non-zero results in cases near the min operating head that previously had a Peak Flow of zero. 

Note, this change will modify/correct results when the reservoir is near the Minimum Operating Head.

**Comment by stighi** [comment]
I ran a test using the January CRMMS-ESP file in RW9.0. Even with updating the Powell.Max Iterations value from 20 to 1000, I still got a few warning messages about reaching the maximum iterations when solving for Peak Flow. The model still solved and did not error out. Any concerns about this?
![image](https://user-images.githubusercontent.com/12956929/215575147-1b9a7eab-bfd5-4e85-8aca-0f7de46b6319.png)
