### ISSUE TITLE
Update Powell values in UBRuleCurveData

### ISSUE THREAD

**Issue by sbaker2423** [usbr/crmms#108]
A few capacity slots in CRMMS have old values: inactive capacity and dead storage in UBRuleCurveData.ReservoirData for Powell.

inactive capacity: 3,742,714.15 acre-ft, which corresponds to 3490'
dead capacity: 1,711,997.35 acre-ft

It doesnt seem like these values are used but it might be good to update them so we dont have old values in the model.

**Comment by stighi** [comment]
Incorporated into v3.4.1 for March 2023 modeling
