### ISSUE TITLE
Powell monthly release distributions for 2023

### ISSUE THREAD

**Issue by stighi** [usbr/crmms#114]
The Powell monthly release table for 2023 only had the 7.0 annual release volume table updated to reflect decisions for 2023. Now that we are projecting balancing releases, we need to modify the monthly releases for 7.48, 8.23, and 9.0 maf as well (possibly 9.5 too?) in order to capture the likely release patterns in 2023.

**Comment by cfelletter** [comment]
Heather says we should just continue with what we are doing in CRMMS, recognizing that we can't capture what has not been decided with regards to balancing in 2023.
