### ISSUE TITLE
Units on HistoricData.Yampa_at_Deerlodge

### ISSUE THREAD

**Issue by cfelletter** [usbr/crmms#115]
HistoricData.Yampa_at_Deerlodge needs to be changed to 1000 AF/mo, input values are in these units not AF/mo. 

PWRE noticed an issue with the February model.  Data in the HistoricData.Yampa_at_Deerlodge slot has the wrong units. Data in this slot is assigned to the YampaRiverInflow.Yampa_at_Deerlodge slot via IR 12 causing incorrect magnitude values in this slot as well. Luckily historical values from these slots are only used to compute the YampaHClass which is not used elsewhere in the rules. Changing the units does not change ESP output 
 
![image](https://user-images.githubusercontent.com/36745146/222554722-c8866e9c-5dd7-4b89-ae80-1b20eddaaaf9.png)

**Comment by stighi** [comment]
Incorporated into v3.4.1 for March 2023 modeling
