### ISSUE TITLE
Potential updates to "Calculate ICS Volumes Available for Delivery NV" rule

### ISSUE THREAD

**Issue by sbaker2423** [usbr/crmms#135]
I noticed that the last two statements seem to have the Trib vs Imp calculations flipped and are setting the other ICS type: 
![image](https://github.com/usbr/crmms/assets/18153871/3eb2e33d-14ec-4aed-b19e-dfb038f6c89f)

**Comment by Ian-Yasui** [comment]
Tributary and and Imp ICS calculations switched to be presenting correctly. Altered in 3.8.0 for rule 37.
