### ISSUE TITLE
Fontenelle Development Updates

### ISSUE THREAD

**Issue by stighi** [usbr/crmms#147]
Michael and Andrew ae discussing some potential updates to Fontenelle rule logic

**Comment by avolkmerBOR** [comment]
Updated changes being implemented at Fontenelle...

Updated safe channel capacity to 10,000 cfs
In FontenelleMonthlyOutflow()
-       For August and September releases, added October 1 target elevation of 6496.5 ft
-	For October release, added November 1 target elevation of 6494 ft
-       For November release, updated timeframe
Updated minimum release values to the following
 
![image](https://github.com/usbr/crmms/assets/117947645/98c83d62-c977-498a-8d11-c1d78c6db0de)

**Comment by stighi** [comment]
Incorporated into operational CRMMS November 2023
