### ISSUE TITLE
LB Evaporation Coefficients

### ISSUE THREAD

**Issue by rabutler-usbr** [usbr/crmms#15]
New evaporation coefficients for Mead and Mohave

not ready until 2020 - low priority

**Comment by rabutler-usbr** [comment]
Previously https://github.com/usbr/MTOM/issues/38

**Comment by stighi** [comment]
Project including peer review, management approval, and stakeholder outreach in final stages. Target rollout is April 2022.

**Comment by stighi** [comment]
Added to model version CRMMS_V1.14.9003.mdl on 3/25/22 for use in the April 2022 studies.
