### ISSUE TITLE
Update UB reservoir live capacity

### ISSUE THREAD

**Issue by sbaker2423** [usbr/crmms#168]
The live capacity needs to be updated as follows (UBRuleCurveData.ReservoirData): 
Blue Mesa 827,940 af
Crystal 17,536 af

The Taylor Park Max Release should also be changed to 1,500 cfs, though the value in this table is not used in the rules. 

Values available in this figure:
https://www.usbr.gov/uc/water/basin/index.html

Other reservoirs seem to have the correct values but have different levels of rounding.

**Comment by stighi** [comment]
Per discussion and investigation with Rick and Alex 3/26/24, use 17,553 af for Crystal.

**Comment by stighi** [comment]
Updated for April 2024 modeling
