### ISSUE TITLE
GJ Local forecast change to regulated

### ISSUE THREAD

**Issue by cfelletter** [usbr/crmms#171]
- [ ] Rick to change forecast spreadsheets to use new Tunnel to GJ stats
- [x] Add comment about new origin of the forecast 
- [ ] HDB mapping from CRMMS is correct SDI
- [ ] Future work: Update slot name and name used in HDB mapping from Crystal to Tunnel to mark new extents. Update spreadsheet names.

**Comment by stighi** [comment]
Implemented in April 2024 modeling
