### ISSUE TITLE
Adjust 'Set Release Tier' rule to not be dependent on WY number

### ISSUE THREAD

**Issue by rabutler-usbr** [usbr/crmms#26]
This rule seems repetitive, as it checks if the model is in WY 1, 2, 3, 4, 5, 6, and performs separate calculations for each. This does not seem necessary and could probably be combined into one If statement for WYs beyond year 1 as the logic is the same. Maybe there was a reason for this repeating logic, but it doesnt seem necessary anymore. I'd proposed updating this rule.

**Comment by rabutler-usbr** [comment]
From @stighi on 2021-03-31T15:17:18Z

We need to be very careful with this. 

We added the logic this way for the following scenarios:
Run start in August & September: 
WY 1 is still currently ongoing and we know what the operations are;
WY 2 has not started yet but has been set by the August 24MS so we know what operating tier we begin at
WY 3 + are open to solving by the model.
Run start in October-December:
WY 1 is the new operating year and we know what the operations are even though it is not the end of the CY 
WY 2 + are open to solving by the model
Run start in January - July:
WY 1 is still ongoing and we know what the operations are - no disconnect between WY & CY
WY 2 + are open to solving by the model

Any changes to this logic need to be thoroughly tested in all run start times. Particularly July through January to make sure Powell doesn't break.

**Comment by rabutler-usbr** [comment]
From @sbaker2423 on 2021-03-31T15:25:09Z

I agree - we'd need to test any changes.  This rule, "Set Release Tier", only sets year 2 and beyond (sorry if this caused any confusion as I was off by a year in the original post). For WY 2, the rules has distinct logic for setting the release tier, but for WY 3 to 6 it repeats its logic. I am just proposing condensing the code for WYs 3-6 to make the code more efficient. 

![SetReleaseTier](https://user-images.githubusercontent.com/18153871/113169519-ea188f00-9202-11eb-9b5d-97fdff10335c.PNG)

**Comment by rabutler-usbr** [comment]
Previously https://github.com/usbr/MTOM/issues/157

**Comment by sbaker2423** [comment]
I ran this development through the dev testing tool and there were zero differences in results.
