### ISSUE TITLE
Run w/ partial input UB operations in ensemble mode

### ISSUE THREAD

**Issue by cfelletter** [usbr/crmms#32]
Run CRMMS w/ CRSP DRO operations input till EOWY but rest of model solves in ensemble mode.

**Comment by stighi** [comment]
Successfully tested and implemented in the August 2021 CRMMS-ESP run. DROA operations set in the Most Probable 24MS were set to remain as Input at Navajo, Flaming Gorge, and Blue Mesa for the timesteps August 2021 - December 2021. Rule logic fired and solved operations at all reservoirs starting in the January 2022 timestep.
