### ISSUE TITLE
LCR-MSCP Compliance Tracking

### ISSUE THREAD

**Issue by stighi** [usbr/crmms#37]
The lower basin states and JP water users are very concerned that Reclamation might be modeling release reductions at Hoover in excess of MSCP compliance levels. They have requested that we add data and/or logic to track delivery reductions for MSCP compliance tracking purposes to CRMMS-24MS (Min, Max, and Most), CRMMS-ESP, and CRSS.

**Comment by apivarnik** [comment]
Added an expression slot to track MSCP compliance in reach 2 between Hoover and Davis. We still have to figure out how to deal with non compliance

**Comment by stighi** [comment]
For tracking non-compliance, we need to update the values of comparison per the new MSCP volumes.
