### ISSUE TITLE
San Juan reservoirs logic needs to be revisited

### ISSUE THREAD

**Issue by stighi** [usbr/crmms#44]
Now that the flow recommendations and operating rules are more set, we need to revisit the Vallecito and Navajo logic

**Comment by cfelletter** [comment]
**List of changes to be moved into Dec/Jan CRMMS Model**
- [ ] J-M VallecitoGuide curve values change to 3655'

Document with my proposed changes to Navajo [](https://doimspp-my.sharepoint.com/:w:/g/personal/cfelletter_usbr_gov/EZtH5M2bsntChDuLMUzjkMIBS2G1YTiLy6OdMW4N0tYPKw?e=Kp3nBD)

**Comment by cfelletter** [comment]
![image](https://user-images.githubusercontent.com/36745146/144342730-c178a5ae-dd74-4f00-b3d9-1a614c755437.png)

**Comment by cfelletter** [comment]
SB comments on January run: So looking at the elevation and outflow, I think the SPRs look good. BUT now I'm worried about the releases outside of that, during irrigation season. I just ran the CRMMS min probable for that exhibit run and Navajo dives into a gigantic shortage. It doesn't look like CRMSS does that for the 90% in the plot above.

**Comment by cfelletter** [comment]
![image](https://user-images.githubusercontent.com/36745146/152544784-9c6e4302-c067-4a24-b7d9-ce4bdae3917e.png)
SB: It's not showing a spring peak release where there shouldn't be one, it's showing a difference in summer releases. CRMMS does not do a good job of calculating summer irrigation releases. It thinks we can release 350 cfs all summer. I have told Conor of this issue, but it's pretty low level I think

**Comment by stighi** [comment]
Comments from SB 3/2022:
I reviewed Navajo, but I have the same comment as usual- the releases in the model are too low in summer irrigation season. For example, the 2012 trace (which was a very dry year) shows a constant summer release of 350 cfs, when in reality it is likely to be closer to 1000 cfs, or even more.  There is no way we could maintain the ESA flows and full irrigation with a release of 350 cfs. When I run the same traces through my MRM I have 3 traces out of 30 that go into a severe shortage and CRMMS doesn't show any shortages because it doesn't know that we need a lot more water in the summer than 350 cfs.   

I realize it's on the list/low priority with staffing shortages but just making a note that it does make a difference when we start looking at very dry traces (which we are now) and paints a bit of a rosy picture with regard to shortage at Navajo.   I'd be glad to work with someone on a fix, we might be able to do something simplistic to at least improve the summer release calculation, but I don't know if anyone has the time right now.

**Comment by cfelletter** [comment]
We could try updating NavajoData.BaseRelease (350) to a higher value as a quick fix. Bumping BaseRelease up to 500 would be a start. @sbehery any thoughts on going higher? MinTargetBaseflow (500) is called initially 
![image](https://user-images.githubusercontent.com/36745146/158251456-44677f87-254b-4ca5-bcaf-f7f853768672.png)
 but then over written by rule DailyOutflowsForNavajo 
![image](https://user-images.githubusercontent.com/36745146/158252037-dc73839c-493a-45e2-81a3-3eab1ab92840.png)
I'm not sure I'll have any availability to test this but @sbaker2423 if you wanted to run a hindcast I could implement the value change (to 500 or whatever @sbehery  says) and help review results. 

We really just need to update Navajo rules. The draft document for how to do so is there it just died on Alan's review desk and now we are short on staff to implement.

**Comment by cfelletter** [comment]
New periodic slot values for BaseRelease
![image](https://user-images.githubusercontent.com/36745146/158625545-767704ed-ef2d-426a-b301-d382c2ffd502.png)

Rules 'SumNavajoOutflowtoMonthly' and 'March through July Daily Release' execution constraint changed so fires in every month (was just start and march but that didn't allow baseflow to update from periodic slot).

Rule 'SumNavajoOutflowtoMonthly' RPL logic simplified, @start timestep and @t = March expression were doing the same thing. I eliminated this redundancy and made it compute every month. 
![image](https://user-images.githubusercontent.com/36745146/158624931-e4abc2dc-9220-43ef-ba3d-721f504935b3.png)

NavajoData.MarchThruJulyDaily should be renamed NavajoData.Daily since it include the who @t - Feb Year + 1 period

**Comment by cfelletter** [comment]
Simulation results (Feb model) 
![image](https://user-images.githubusercontent.com/36745146/158638380-d6850238-4fc8-43ab-8c11-b263865a9176.png)
![image](https://user-images.githubusercontent.com/36745146/158638406-c37cc9d2-1b3d-44e9-876b-452ad3d14601.png)
![image](https://user-images.githubusercontent.com/36745146/158638429-75e17e39-506c-4c96-aa2a-ad3cbe49db10.png)

**Comment by cfelletter** [comment]
- [ ] Update Vallecito Max Release to 2200 cfs. Currently the spillway is not available for use while it under goes major repairs. Susan anticipates this will be on going for next ~5 years. 
- [ ] Change max PE target to 7664 for the same reason
![image](https://user-images.githubusercontent.com/36745146/223563045-1195ef05-7232-498b-b9a5-b54e8ce1ff8c.png)
Change the highlighted to 7664' and 22 ksf
