### ISSUE TITLE
Add LC flag slots for output automation

### ISSUE THREAD

**Issue by stighi** [usbr/crmms#49]
Add the following flag slots to the model and output DMI and control file:
- MSCP Compliance violation
- Mead below elevation 950 in any month
- Mead below elevation 895 in any month
- Mead below 1025 at EOCY
- Mead below 1045 at EOCY
- Mead below 1050 at EOCY

**Comment by sbaker2423** [comment]
Could we also add the evaporation volume for all reservoirs? This could be added to 'res.rdf'

**Comment by stighi** [comment]
Yes, absolutely!

**Comment by stighi** [comment]
Actually, now that we are going to be using CRMMS for the 5-year tables, do we also need to add flags for Mead < 1020 in any month and Mead < 1030 in any month? Any other flags that are in CRSS that we need to add to CRMMS?

**Comment by rabutler-usbr** [comment]
Can or can't. It's very helpful to have the tiers as binary flags since those are relatively static. But for chances of falling below different elevations in any month vs ecoy, vs wy etc. we handle all those as a post process since they change so much depending on what the analysis is.

**Comment by apivarnik** [comment]
Closed 57aaefaf02c7f3bc9605000b5444c9afa74204e8
