### ISSUE TITLE
Add evap to res.rdf

### ISSUE THREAD

**Issue by rabutler-usbr** [usbr/crmms#57]
Please add evaporation slot to the res.rdf output. I'm pretty sure only Powell.Evaporation is in it.

**Comment by stighi** [comment]
The output.control file on Github in the Dev branch includes evaporation for all reservoirs as well as a bunch of Mead annual flags. For some reason the updated file on Github did not get incorporated into the production files for February. We have taken steps to make sure we use the updated control file in March and going forward.
