### ISSUE TITLE
Update Mead Base Flow Table

### ISSUE THREAD

**Issue by sbaker2423** [usbr/crmms#97]
I am having runs abort due to the power method at Lake Mead. This occurs when Mead's outflow is zero and RW is trying to solve the Peak and Base Power method. I reached out to CADSWES and they have more info and a fix: 

> The problem is partially due to a bug in the Peak and Base method, but there is also a necessary change to the Mead.Base Flow Table. Fortunately, there is an easy workaround.
> 
> The method does a lookup on the Base Flow Table to determine the Base Flow. The lookup does not work correctly when the Outflow is exactly equal to one of the rows in the table, in this case Outflow is 0.00 cfs, which is the first row in the table.
> 
> The workaround is to make the Outflow for the first row in the table a negative value with a Base Flow of zero. That way the Outflow slot value of zero will be greater than the value in the first row, and the lookup will work as intended. Currently the table has a Base Flow of 1 acre-ft/month for an Outflow of zero. You cannot have a Base Flow greater than Outflow. You need your table to have something like
![image](https://user-images.githubusercontent.com/18153871/206719726-4ce3aea5-14f7-4cf7-84d4-22b07e6f89d9.png)
> 
> You might want to use a different Base Flow for the range from 1 cfs to 5,000 cfs. To do so, you would need to add in another row, but you need to make sure the Base Flow is always less than Outflow (noticing the difference in display units).
> 
> We need to discuss here what we want to do about fixing the bug.

To enable the model to iterate in the Peak and Base method, I also had to update the Best Generator Flow and Best Generator Power tables. I update the tables to this in an analysis model:
![image](https://user-images.githubusercontent.com/18153871/210098127-0cc5b72d-53d9-4d80-925d-4c253561760b.png)

**Comment by stighi** [comment]
Updates made to operational model files in v 3.1.0.9002 and committed on 12/30/22
